mkdir run_pars_1
mkdir run_pars_2
mkdir run_pars_3
mkdir run_pars_4
mkdir run_pars_5
mkdir run_pars_6
mkdir run_pars_7
mkdir run_pars_8
mkdir run_pars_9
mkdir run_pars_10
mkdir run_pars_11
mkdir run_pars_12
mkdir run_pars_13
mkdir run_pars_14
mkdir run_pars_15
mkdir run_pars_16
mkdir run_pars_17
mkdir run_pars_18
mkdir run_pars_19
mkdir run_pars_20
mkdir run_pars_21
mkdir run_pars_22
mkdir run_pars_23
mkdir run_pars_24
mkdir run_pars_25
mkdir run_pars_26
mkdir run_pars_27
mkdir run_pars_28
mkdir run_pars_29
mkdir run_pars_30
mkdir run_pars_31
mkdir run_pars_32
mkdir overall
mkdir overall/uninformative
mkdir overall/informed
mkdir overall/low
mkdir overall/uninformative/withvax
mkdir overall/informed/withvax
mkdir overall/low/withvax
