run_pars_list <- list(
	# UNINFORMATIVE PRIORS: ---------------------------------------------------
	# 1) Confirmed omicron against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 2) Suspected omicron against everyone else: 
	list(excluded_rows=c(),
		special_rows=c(filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
			filter(ct_dat_refined, GreekLineage=="Suspected Omicron")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 3) Suspected omicron against delta 
	list(excluded_rows=c(filter(ct_dat_refined, !(GreekLineage%in%c("Omicron","Suspected Omicron","Delta")))$RowID),
		special_rows=c(filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
			filter(ct_dat_refined, GreekLineage=="Suspected Omicron")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# PRIORS INFORMED BY PREVIOUS ANALYSIS: -----------------------------------
	# 4) Confirmed omicron against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 5) Suspected omicron against everyone else: 
	list(excluded_rows=c(),
		special_rows=c(filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
			filter(ct_dat_refined, GreekLineage=="Suspected Omicron")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 6) Suspected omicron against delta
	list(excluded_rows=c(filter(ct_dat_refined, !(GreekLineage%in%c("Omicron","Suspected Omicron","Delta")))$RowID),
		special_rows=c(filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
			filter(ct_dat_refined, GreekLineage=="Suspected Omicron")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# LOW PRIORS: -------------------------------------------------------------
	# 7) Confirmed omicron against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 8) Suspected omicron against everyone else: 
	list(excluded_rows=c(),
		special_rows=c(filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
			filter(ct_dat_refined, GreekLineage=="Suspected Omicron")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 9) Suspected omicron against delta 
	list(excluded_rows=c(filter(ct_dat_refined, !(GreekLineage%in%c("Omicron","Suspected Omicron","Delta")))$RowID),
		special_rows=c(filter(ct_dat_refined, GreekLineage=="Omicron")$RowID,
			filter(ct_dat_refined, GreekLineage=="Suspected Omicron")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		)
	)
	
